# Generated by Django 4.1.3 on 2023-02-12 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('search', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('thumbnail', models.URLField()),
                ('view_count', models.IntegerField()),
                ('keywords_tags', models.TextField()),
                ('duration_seconds', models.IntegerField()),
                ('upload_date', models.DateField()),
                ('published_time', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('all_video_description', models.TextField()),
                ('channel', models.CharField(max_length=200)),
                ('subscribers', models.CharField(max_length=50)),
                ('channel_description', models.TextField(null=True)),
                ('keywords_channel', models.TextField()),
                ('channel_total_views', models.IntegerField()),
                ('channel_join', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
