# Generated by Django 4.1.3 on 2023-02-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
