# Generated by Django 4.1.3 on 2023-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='channel_total_views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='keywords_tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='published_time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
